### ISSUE TITLE
Error Attempting to Configure Data Source

### ISSUE THREAD

**Issue by juarezjx** [HadesArchitect/grafana-cassandra-source#13]
After installation, unzipping grafana-cassandra-source-master.zip to /var/lib/grafana/plugin/cassandra I do see the data source under plugins on the web interface.  

When I click "Apache Cassandra" under Configurations I get a continuous "loading" message.  Also when I click "Apache Cassandra" from datastores I get the error message in the image below. 

Unexpected token '<' Evaluating http://localhost:3000/public/plugins/hadesarchitect-cassandra-datasource/module.js Loading plugins/hadesarchitect-cassandra-datasource/module

Any assistance would be appreciated.  We are trying to use Grafana on top of Cassandra.

**Comment by juarezjx** [comment]
<img width="1773" alt="Capture" src="https://user-images.githubusercontent.com/29693044/82389280-989f5100-99f0-11ea-906d-92d675493983.PNG">

**Comment by juarezjx** [comment]
<img width="891" alt="Capture2" src="https://user-images.githubusercontent.com/29693044/82389321-b8367980-99f0-11ea-960a-86158bfd19e7.PNG">

**Comment by juarezjx** [comment]
Some additional information from /var/log/grafana/grafana.log

_t=2020-05-19T17:17:33-0700 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=hadesarchitect-cassandra-datasource error="fork/exec /var/lib/grafana/plugins/cassandra/src/cassandra-plugin_linux_amd64: no such file or directory"_

**Comment by HadesArchitect** [comment]
@juarezjx Hello and thank you for the Bug report! I'll investigate it asap.

**Comment by HadesArchitect** [comment]
Hello @juarezjx Could you please try to install the plugin using zip or tar packages of the release 0.1.7? https://github.com/HadesArchitect/grafana-cassandra-source/releases/tag/0.1.7

**Comment by HadesArchitect** [comment]
Not the source code but release packages, `cassandra-datasource-0.1.7.zip`

**Comment by juarezjx** [comment]
Hi Aleks,
This worked with Grafana version 6.6.2-1!  Thanks for the very quick reply.  

For Grafana version 7.0.0-1 I was getting an error 
_"Failed to load plugin" logger=plugins error="plugin \"hadesarchitect-cassandra-datasource\" is unsigned" pluginPath=/var/lib/grafana/plugins/dist_, which I will dig into tomorrow.  

I did modify _;allow_loading_unsigned_plugins = hadesarchitect-cassandra-datasource_ in /etc/grafana/grafana.ini.  No luck there.

**Comment by HadesArchitect** [comment]
Hi @juarezjx, I'm very sad to say the plugin supports grafana version  only < 7.* They have heavily reworked the whole plugin system architecture in the version 7.0 so this plugin works with version up to 6.* so far. I'll keep working to make it compatible (though it looks like it has to be developed almost from scratch).

I'll close this issue, please feel free to reopen.
