### ISSUE TITLE
Cassandra query not working through cassandra datasource plugin

### ISSUE THREAD

**Issue by mbhatnagar21** [HadesArchitect/grafana-cassandra-source#19]
Cassandra table structure - MONITOR_DATA(resourceId text, paramName text, interfaceType text, type text, value_datatype text, value_of_resource text, unit text, timeStamp timestamp, PRIMARY KEY((resourceId,paramName),timeStamp))with clustering order by(timeStamp desc)

I am trying to create a query on the cassandra dashboard on grafana plugin , below are the fields that I am filling :

keyspace - mykeyspace , table - monitor_data,
Time column - timestamp , Value Column - value_of_resource,
ID Column - paramname , ID Vaue - 

What am I supposed to fill in the ID Value , its expecting some kind of column UUID in input and because of this the query is failing if I check in Query Inspector. How can I get column UUID?

error message in query inspector = message:"Invalid UUID constant (0f770291-90c3-4952-98f8-324ffd81eac4) for "paramname" of type text" 
(I tried filling the UUID with some random value).

Any help would be appreciated.
Thanks.

**Comment by HadesArchitect** [comment]
Hello @mbhatnagar21, thank you for your interest in the project. At this point, the plugin is in the early stage and only supports very simple tables with only one primary key field, yours have a composite primary key `(resourceId,paramName), timeStamp)`. This is a very often use-case so it's the next thing to implement. I hope to add it next week with a solution for #14. 

To be released as `0.2.0`
