### ISSUE TITLE
Documentation of unsigned plugin workaround

### ISSUE THREAD

**Issue by derrickoswald** [HadesArchitect/grafana-cassandra-source#21]
Since the plugin is not signed, Grafana will [not load it by default](https://github.com/grafana/grafana/issues/24027).

To work-around this issue add the following in the plugins section of **/etc/grafana/grafana.ini**

```
[plugins]
# Enter a comma-separated list of plugin identifiers to identify plugins that are allowed to be loaded even if they lack a valid signature.
allow_loading_unsigned_plugins = "hadesarchitect-cassandra-datasource"
```

This could be added to the README.md with little effort.

**Comment by HadesArchitect** [comment]
Thank you @derrickoswald, I'll update docs based on your suggestion
