### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY

### ISSUE THREAD

**Issue by DevAleks** [HadesArchitect/grafana-cassandra-source#9]
After git clone and execution `docker run -v ${PWD}:/opt/gcds -w /opt/gcds node npm install` I see the following
![scr3](https://user-images.githubusercontent.com/58343508/72284596-7072a080-3652-11ea-9cf0-6c1343a6e367.png)
May be its needs to fix.

**Comment by HadesArchitect** [comment]
It's very fine in the current state, I'll close it for now.
